# -*- coding: utf-8 -*-
name: Send Commit Message to Notion

on:
  push:
    branches:
      - main

env:
  TITLE_PROPERTY_NAME: "제목"
  URL_PROPERTY_NAME: "문제 풀이 링크"
  USER_PROPERTY_NAME: "푼 사람"

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: true

      - name: Set Git encoding
        run: |
          git config --global core.quotepath off
          git config --global gui.encoding utf-8
          git config --global i18n.commit.encoding utf-8
          git config --global i18n.logoutputencoding utf-8

      - name: Get Source Code File
        id: get_source_code_file
        if: contains(github.event.head_commit.message, 'ms, Memory:')
        run: |
          # 변경된 파일 목록 가져오기
          CHANGED_FILES=$(git diff --name-only HEAD^)

          # 찾는 확장자의 파일 정보를 가져옵니다
          CODE_FILES=$(echo "$CHANGED_FILES" | grep -vE '\.md$' || true)

          # 찾은 파일 중 첫번째 파일의 정보를 가져옵니다
          FIRST_FILE=$(echo "$CODE_FILES" | head -n 1)

          FILE_NAME=$(basename "$FIRST_FILE")
          FILE_NAME_WITHOUT_EXTENSION=${FILE_NAME%.*}
          FILE_PATH=$(echo -n "$FIRST_FILE" | jq -sRr @uri)
          echo $FILE_NAME_WITHOUT_EXTENSION

          # 링크 정보를 가져옵니다
          REPO_URL="https://github.com/${{ github.repository }}"
          FILE_URL="${REPO_URL}/blob/${{ github.ref }}/$FILE_PATH"
          echo $FILE_URL

          # 변수를 담습니다.
          echo "TITLE=${FILE_NAME_WITHOUT_EXTENSION}" >> $GITHUB_ENV
          echo "FILE_URL=${FILE_URL}" >> $GITHUB_ENV

      - name: Send Commit Message to Notion
        if: contains(github.event.head_commit.message, 'ms, Memory:')
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_USER_ID: ${{ secrets.NOTION_USER_ID }}
        run: |
          curl -X POST https://api.notion.com/v1/pages \
            -H "Authorization: Bearer $NOTION_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data-binary '{
                  "parent": { "database_id": "'$NOTION_DATABASE_ID'" },
                  "properties": {
                    "'"$TITLE_PROPERTY_NAME"'": {
                      "title": [
                        {
                          "text": {
                            "content": "'"$TITLE"'"
                          }
                        }
                      ]
                    },
                    "'"$URL_PROPERTY_NAME"'": {
                      "url": "'"$FILE_URL"'"
                    },
                    "'"$USER_PROPERTY_NAME"'": {
                      "people": [{
                        "id": "'"$NOTION_USER_ID"'"
                      }]
                    }
                  }
                }'
